use gali;
create table ATM(ID INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(100),PASSWORD VARCHAR(100),BALANCE FLOAT);
insert into ATM(ID,NAME,PASSWORD,BALANCE) Values(101,"GALI SATEESH","Sateesh(542)",10000);
insert into ATM(ID,NAME,PASSWORD,BALANCE) Values(103,"Vishnu","Vishnu123",30000);
select * from ATM;

